---
title: "Bipartite Network Construction"
output: html_notebook
author: Charles Sither
date: 7/15/2024
---


```{r}
library(vegan)
library(bipartite)
library(igraph)
library(dplyr)
library(data.table) # for the setnames() function which makes column renaming with a map file trivial
```



```{r}
# Set the working directory path
wk_dir <- "C:/Users/cbsit/Dropbox/NCSU_Coursework/Research/Publications/Larval_Hab_Pub/Larval_Habitat_Pub/"

# Concatenate the working directory path with the file name
csv_dat <- paste0(wk_dir, "data/cleaned_data/cleaned_unique_species_hab_matrix.csv")

# Print the CSV file path to verify
print(csv_dat)
```


```{r}
file.exists(csv_dat)

df <- read.csv(csv_dat, header = TRUE)
```

```{r}
df_raw <- df
```

```{r}
colnames(df)
```


```{r}
# rename habitat columns
habitat_map <- read.csv(paste0(wk_dir, "data/raw_data/habitat_map.csv"))
str(habitat_map)
rename_map <- setNames(as.character(habitat_map$Name), as.character(habitat_map$Acrynoym))

habitat_map
rename_map

```


```{r}
# rename columns
setnames(df, old = habitat_map$Acronym, new = habitat_map$Name)
```

```{r}
colnames(df)
```



```{r}
# Extract genus names
df$Genus <- sapply(strsplit(as.character(df$Genus_Species), "_"), `[`, 1)
```


```{r}
# Aggregate the data by genus and habitat
df_agg <- df %>%
  group_by(Genus) %>%
  summarise(across(-Genus_Species, sum))
```

```{r}
df_agg$Genus
```

```{r}
# Define the desired order of genera
desired_order_genus <- c("Aedeomyia", "Aedes", "Psorophora", "Armigeres", 
                         "Eretmapodites", "Haemagogus", "Heizmannia", 
                         "Opifex", "Verrallina", "Anopheles", "Bironella", 
                         "Chagasia", "Mansonia", "Coquillettidia", "Culex", 
                         "Deinocerites", "Lutzia", "Culiseta", "Ficalbia", 
                         "Mimomyia", "Hodgesia", "Isostomyia", "Johnbelkinia", 
                         "Kimia", "Limatus", "Malaya", "Maorigoeldia", 
                         "Onirion", "Runchomyia", "Sabethes", "Shannoniana", 
                         "Topomyia", "Trichoprosopon", "Tripteroides", "Wyeomyia", 
                         "Orthopodomyia", "Toxorhynchites", "Uranotaenia")

# Filter the desired order to match the genera present in df_agg
desired_order_genus <- desired_order_genus[desired_order_genus %in% df_agg$Genus]

# Define the desired order of habitats
desired_order_habitat <- c("Artificial Containers","Bamboo", "Fruit Husks", "Flower Parts", "Fallen Plant Parts", 
                           "Leaf Axils", "Modified Leaves", "Tree Holes", "Animal Tracks", 
                           "Brackish Pools", "Coral Rockpools", "Crab Holes", "Drainage Pools", 
                           "Ditches", "Ground Pools", "Brackish Ground Pools", "Temporary Ground Pools", 
                           "Hog Wallows", "Irrigation Canals/Channels", "Lagoons", "Lake Margins", 
                           "Brackish Marshes", "Marshes", "Ponds", "Pond Margins", 
                           "Rice Field/Paddies", "Roadside Pools", "River Margins", "Rockpools", 
                           "Brackish Rockpools", "Seepages", "Snowmelt Pools", "Springs", 
                           "Streams", "Stream Margin Overflow", "Rocky Stream Margins", "Intermittent Streams", 
                           "Swamps")

# Convert to incidence matrix
incidence_matrix <- as.matrix(df_agg[, -1])
rownames(incidence_matrix) <- df_agg$Genus

# Filter out genera not present in the data
desired_order_filtered_genus <- desired_order_genus[desired_order_genus %in% rownames(incidence_matrix)]

# Reorder the rows based on the desired order
incidence_matrix <- incidence_matrix[match(desired_order_filtered_genus, rownames(incidence_matrix)), ]

# Ensure the desired habitat order matches the columns present in your incidence_matrix
desired_order_filtered_habitat <- desired_order_habitat[desired_order_habitat %in% colnames(incidence_matrix)]

# Reorder the columns based on the desired order
incidence_matrix <- incidence_matrix[, match(desired_order_filtered_habitat, colnames(incidence_matrix))]

# Remove rows and columns that are entirely zero
incidence_matrix <- incidence_matrix[rowSums(incidence_matrix) > 0, ]
incidence_matrix <- incidence_matrix[, colSums(incidence_matrix) > 0]

# Check the incidence matrix
print(incidence_matrix)
```

```{r, fig.height=20, fig.width=20}
# Plot the bipartite network with genus on the left and habitats on the right

svg(paste0(wk_dir, "figures/raw/bipartite_network.svg"), height=15, width=30)

plotweb(incidence_matrix,
        method = "normal",          # method for plotting
        labsize = 1,                # size of the labels
        ybig = 1,                   # vertical spacing between levels
        low.spacing = 0.005,
        high.spacing = 0.005,
        col.interaction = "lightblue",   # color of the interactions (edges)
        bor.col.interaction = "blue",
        bor.col.high = "orange",       # color of the higher level (columns)
        bor.col.low = "green",       # color of the lower level (genus)
        text.rot = 90,              # rotate text to be vertical,    # color for high abundance
        high.lablength = 10,        # length of the labels for higher level
        low.lablength = 10,         # length of the labels for lower level
        col.low = "green",
        col.high = "orange"
        
        )

dev.off()

```

